### ISSUE TITLE
Configurable GPIO pins

### ISSUE THREAD

**Issue by fruit-bat** [carlk3/no-OS-FatFS-SD-SPI-RPi-Pico#11]
Firstly, thanks for publishing this. I am using it on my mini-project (https://github.com/fruit-bat/pico-sorcerer-2) and it works really well.

I would love to be able to configure the GPIO pins without having to modify the source code... my sub-module on github won't have the changes needed for other people to download and compile. 

Thanks in advance,

fruit-bat

**Comment by carlk3** [comment]
I removed `hw_config.c` from the `FatFs_SPI` library, since I can see how that would interfere with using the library as a submodule. Now, you can define the functions declared in `FatFs_SPI/sd_driver/hw_config.h` wherever and however you'd like. 

I added an example showing how you might set up the configuration at run time.

I have opened a pull request: https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/pull/12#issue-988611933. Please take a look.

**Comment by fruit-bat** [comment]
Many thanks for the changes, much appreciated.
I will try them out as soon as I get a  chance and get back to you....
